### ISSUE TITLE
Data visualization code issues

### ISSUE THREAD

**Issue by wwwpkol** [facebookresearch/AGRoL#19]
Traceback (most recent call last):
File "/home/yyh_file/AGRol-main/vis.py", line 94, in
main(opt)
File "/home/yyh_file/AGRol-main/vis.py", line 75, in main
avg_error = evaluate(opt, logger, model, test_loader, save_animation=1)
File "/home/yyh_file/AGRol-main/test.py", line 41, in evaluate
vis.save_animation(body_pose=predicted_body, savepath=save_video_path_gt, bm = body_model.body_model, fps=fps, resolution = (800,800))
File "/home/yyh_file/AGRol-main/utils/utils_visualize.py", line 174, in save_animation
mv = MeshViewer(width=imw, height=imh, use_offscreen=True)
File "/home/yyh_file/AGRol-main/body_visualizer/mesh/mesh_viewer.py", line 59, in init
self.viewer = pyrender.OffscreenRenderer(*self.figsize)
File "/home/.conda/envs/AGRol/lib/python3.9/site-packages/pyrender/offscreen.py", line 31, in init
self._create()
File "/home/.conda/envs/AGRol/lib/python3.9/site-packages/pyrender/offscreen.py", line 137, in _create
egl_device = egl.get_device_by_index(device_id)
File "/home/.conda/envs/AGRol/lib/python3.9/site-packages/pyrender/platforms/egl.py", line 83, in get_device_by_index
raise ValueError('Invalid device ID ({})'.format(device_id, len(devices)))
ValueError: Invalid device ID (0)

Thanks for your work, but sadly there seems to be a problem with the pose visualization code. Have you encountered such a problem? Or how to solve it. thank you for your reply！

**Comment by asanakoy** [comment]
Looks like the problem is in pyrender. Try upgrading/ reinstaling?

**Comment by wwwpkol** [comment]
> Looks like the problem is in pyrender. Try upgrading/ reinstaling?

Thanks for your suggestion, I reinstalled twice and this problem no longer occurs.
But I encountered the following problem.

  File "/home/JLM_m/body_visualizer/mesh/mesh_viewer.py", line 59, in __init__
    self.viewer = pyrender.OffscreenRenderer(*self.figsize)
  File "/home/.conda/envs/vis_SMPL/lib/python3.8/site-packages/pyrender/offscreen.py", line 31, in __init__
    self._create()
  File "/home/.conda/envs/vis_SMPL/lib/python3.8/site-packages/pyrender/offscreen.py", line 149, in _create
    self._platform.init_context()
  File "/home/.conda/envs/vis_SMPL/lib/python3.8/site-packages/pyrender/platforms/egl.py", line 177, in init_context
    assert eglInitialize(self._egl_display, major, minor)
  File "/home/.conda/envs/vis_SMPL/lib/python3.8/site-packages/OpenGL/platform/baseplatform.py", line 402, in __call__
    return self( *args, **named )
  File "/home/.conda/envs/vis_SMPL/lib/python3.8/site-packages/OpenGL/error.py", line 228, in glCheckError
    raise GLError(
OpenGL.error.GLError: GLError(
        err = 12289,
        baseOperation = eglInitialize,
        cArguments = (
                <OpenGL._opaque.EGLDisplay_pointer object at 0x7f28b76e84c0>,
                c_long(0),
                c_long(0),
        ),
        result = 0
)

**Comment by wwwpkol** [comment]
> Looks like the problem is in pyrender. Try upgrading/ reinstaling?

Thanks for your suggestion, I reinstalled twice and this problem no longer occurs.
But I encountered the following problem.

File "/home/body_visualizer/mesh/mesh_viewer.py", line 59, in init
self.viewer = pyrender.OffscreenRenderer(*self.figsize)
File "/home/.conda/envs/vis_SMPL/lib/python3.8/site-packages/pyrender/offscreen.py", line 31, in init
self._create()
File "/home/.conda/envs/vis_SMPL/lib/python3.8/site-packages/pyrender/offscreen.py", line 149, in _create
self._platform.init_context()
File "/home/.conda/envs/vis_SMPL/lib/python3.8/site-packages/pyrender/platforms/egl.py", line 177, in init_context
assert eglInitialize(self._egl_display, major, minor)
File "/home/.conda/envs/vis_SMPL/lib/python3.8/site-packages/OpenGL/platform/baseplatform.py", line 402, in call
return self( *args, **named )
File "/home/.conda/envs/vis_SMPL/lib/python3.8/site-packages/OpenGL/error.py", line 228, in glCheckError
raise GLError(
OpenGL.error.GLError: GLError(
err = 12289,
baseOperation = eglInitialize,
cArguments = (
<OpenGL._opaque.EGLDisplay_pointer object at 0x7f28b76e84c0>,
c_long(0),
c_long(0),
),
result = 0
)

**Comment by cxTAKA** [comment]
File "C:\Users\TAKA\anaconda3\envs\py37torch17\lib\site-packages\pyrender\platforms\egl.py", line 183, in init_context
    assert eglBindAPI(EGL_OPENGL_API)
  File "C:\Users\TAKA\anaconda3\envs\py37torch17\lib\site-packages\OpenGL\platform\baseplatform.py", line 402, in __call__
    return self( *args, **named )
  File "C:\Users\TAKA\anaconda3\envs\py37torch17\lib\site-packages\OpenGL\error.py", line 232, in glCheckError
    baseOperation = baseOperation,
OpenGL.error.GLError: GLError(
	err = 12300,
	baseOperation = eglBindAPI,
	cArguments = (EGL_OPENGL_API,),
	result = 0
)
similar problem , but different error index.

**Comment by Sunwenxin1** [comment]
> > Looks like the problem is in pyrender. Try upgrading/ reinstaling?
> 
> Thanks for your suggestion, I reinstalled twice and this problem no longer occurs. But I encountered the following problem.
> 
> File "/home/body_visualizer/mesh/mesh_viewer.py", line 59, in init self.viewer = pyrender.OffscreenRenderer(*self.figsize) File "/home/.conda/envs/vis_SMPL/lib/python3.8/site-packages/pyrender/offscreen.py", line 31, in init self._create() File "/home/.conda/envs/vis_SMPL/lib/python3.8/site-packages/pyrender/offscreen.py", line 149, in _create self._platform.init_context() File "/home/.conda/envs/vis_SMPL/lib/python3.8/site-packages/pyrender/platforms/egl.py", line 177, in init_context assert eglInitialize(self._egl_display, major, minor) File "/home/.conda/envs/vis_SMPL/lib/python3.8/site-packages/OpenGL/platform/baseplatform.py", line 402, in call return self( *args, **named ) File "/home/.conda/envs/vis_SMPL/lib/python3.8/site-packages/OpenGL/error.py", line 228, in glCheckError raise GLError( OpenGL.error.GLError: GLError( err = 12289, baseOperation = eglInitialize, cArguments = ( <OpenGL._opaque.EGLDisplay_pointer object at 0x7f28b76e84c0>, c_long(0), c_long(0), ), result = 0 )

i also met this problem. did you solve it?

**Comment by Minions-Bob** [comment]
Have you resolved this issue? I am encountering the same error as well.

**Comment by Minions-Bob** [comment]
> > > 看起来问题出在 pyrender 中。尝试升级/重新安装？
> > 
> > 
> > 感谢您的建议，我重新安装了两次，此问题不再出现。但是我遇到了以下问题。
> > 文件 “/home/body_visualizer/mesh/mesh_viewer.py”，第 59 行，init self.viewer = pyrender 中。OffscreenRenderer（*self.figsize） 文件 “/home/.conda/envs/vis_SMPL/lib/python3.8/site-packages/pyrender/offscreen.py”，第 31 行，在 init self._create（） 文件中 “/home/.conda/envs/vis_SMPL/lib/python3.8/site-packages/pyrender/offscreen.py”，第 149 行，在 _create self._platform.init_context（） 文件中 “/home/.conda/envs/vis_SMPL/lib/python3.8/site-packages/pyrender/platforms/egl.py”，第 177 行，init_context assert eglInitialize（self._egl_display， 主要，次要） 文件 “/home/.conda/envs/vis_SMPL/lib/python3.8/site-packages/OpenGL/platform/baseplatform.py”，第 402 行，调用 return self（ *args， **named ） 文件“/home/.conda/envs/vis_SMPL/lib/python3.8/site-packages/OpenGL/error.py”，第 228 行，在 glCheckError 中引发 GLError（ OpenGL.error.GLError： GLError（ err = 12289， baseOperation = eglInitialize， cArguments = （ <OpenGL._opaque.EGLDisplay_pointer 0x7f28b76e84c0> 处的对象，c_long（0）， c_long（0）， ）， 结果 = 0 ）
> 
> 我也遇到了这个问题。您解决了吗？

**Comment by Minions-Bob** [comment]
Have you resolved this issue? I am encountering the same error as well.
